[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astrea"
version = "3.9.0"
description = "Astrophysical Shockwave and Turbulence REsearch for interstellar Applications: Multidimensional magnetohydrodynamics code for modelling shockwaves & turbulence in the interstellar medium"
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
  { name = "Mervin Yap", email = "myap@ph1.uni-koeln.de" }
]

dependencies = [
    "gitpython",
    "h5py",
    "matplotlib",
    "mpi4py",
    "numba",
    "numpy>=2.0.0",
    "nvidia-ml-py3",
    "psutil",
    "pycairo",
    "python-dotenv",
    "pyyaml",
    "scikit-image",
    "scipy",
    "tabulate",
    "threadpoolctl",
    "tinydb",
]

keywords = [
    "computational astrophysics",
    "astrophysics",
    "interstellar medium",
    "computational fluid dynamics",
    "fluid dynamics",
    "finite volume method",
    "numerical methods"
    "Riemann solver",
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Operating System :: Linux",
    "Operating System :: MacOS (ARM/Intel)"
]

[project.urls]
homepage = "https://github.com/mervyzr/astrea"
issues = "https://github.com/mervyzr/astrea/issues"

[tool.setuptools.packages.find]
include = ["astrea*"]
exclude = [
    "saved_data",
    ".vidplots",
    "krome",
]

[tool.setuptools.package-data]
astrea = [
    "*.py",
    "*.yml",
    "*.json",
    "*.gif",
    "*.txt",
    "*.dat"
]