# Test configurations
# : Sod, Sedov, Shu-Osher, sin wave, square wave, Toro1/2/3/4/5
config: 'sod'

# Shock tube parameters
cells: 200
cfl: .5
gamma: 1.4

# Numerical methods
# : PCM, PLM, PPM
solver: 'ppm'
# : Euler, RK4, SSPRK(2,2), SSPRK(3,3), SSPRK(4,3), SSPRK(5,3), SSPRK(5,4)
timestep: 'ssprk(5,4)'

# Runtime parameters
# : Single, Multiple
runType: 'single'
livePlot: False

# Media options
savePlots: False
snapshots: 1
saveVideo: False
saveFile: False