---
# List of available configurations (spaces are hyphenated)
#   Smooth: sine wave, Gaussian, manufactured Euler solution (Euler), circular polarised Alfvén wave (CPAW)
#   Shocktubes: Sod shock, slow-moving shock, Shu-Osher (OS), Ryu-Jones (RJ), Brio-Wu (BW), Toro 1-5
#   Blastwaves: Sedov, MHD blast, Noh problem
#   Vortices: MHD vortex, Orszag-Tang vortex, Gresho vortex, isentropic vortex (IVC)
#   Instabilities: (MHD) Rayleigh-Taylor instability (RTI), (MHD) Kelvin-Helmholtz instability (KHI)
#   Non-linear MHD: MHD rotor, MHD current, MHD blob
#   Astrophysical: Shock cloud, astrophysical jet, MHD torus, supernova (SN)
#   2D Riemann: Yee-Sjögreen (YS), (MHD) Lax-Liu 1-19
#   Turbulent/random noise: turbulence, blank field

physics_parameters:
  config        : Sedov
  cells         : 128
  cfl           : .5
  gamma         : 1.4
  dimensions    : 2
  units         : code
  gravity       : false

numerical_parameters:
  # Subgrid models for hydro and mag. components : PCM, PLM, PPM, CWENO, WENO-Z, WENO-3/5/7
  subgrid       : PCM
  # Iteration methods : EULER, RK4, SSPRK(2,2), SSPRK(3,3), SSPRK(4,3), SSPRK(5,3), SSPRK(5,4), SSPRK(10,4), SSPRK(6,5)
  time_evo      : EULER
  # Update schemes : Lax-Friedrich (LF), Lax-Wendroff (LW), GFORCE (G), HLL, HLLC (C), HLLD (D), Osher-Solomon (OS)
  solver        : LF

runtime_parameters:
  checkpoints   : 1
  live_plot     : false
  save_snaps    : false
  save_plots    : false
  save_video    : false
  save_file     : false
  plot_style    : default
  # Plot options
  # : density, pressure, velocity Vx/Vy/Vz, total/internal energy, Mach number,
  # : magnetic field Bx/By/Bz, magnetic pressure, magnetic divergence divB
  plot_options  :
    - density
    - pressure
    - vx
    - total energy
...